specVersion: 1.0.0
name: subql-xcm-karura
version: 1.0.0
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: >-
  Index xcmp related data on Karura parachain
repository: 'https://github.com/serkul/subql-xcm-karura.git'
schema:
  file: ./schema.graphql
network:
  chainId: '0xbaf5aabe40646d11f0ee8abbdc64f4a4b7674925cba08e4a05ff9ebed6e2126b'
  endpoint: 'wss://karura.api.onfinality.io/public-ws'
  dictionary: https://api.subquery.network/sq/subquery/karura-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1702399
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleXcmpQueueModule
          kind: substrate/EventHandler
          filter:
            module: xcmpQueue
        - handler: handleDmpParaEvent
          kind: substrate/EventHandler
          filter:
            module: dmpQueue
            method: ExecutedDownward
        - handler: handleUmpParaEvent #check is made inside handler to not repeat handleXcmpQueueModule
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: Transferred    
        - handler: handleUmpParaEvent #check is made inside handler to not repeat handleXcmpQueueModule
          kind: substrate/EventHandler
          filter:
            module: xTokens
            method: TransferMultiAssets    
